// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using AVFoundation;
using CoreFoundation;
using CoreMedia;
using CoreImage;
using System.Collections.Generic;

namespace ClipperIOS
{
	public partial class CameraViewController : UIViewController//, IAVCaptureVideoDataOutputSampleBufferDelegate
	{
        public bool CameraPermisiion;
        public bool takePicture = false;
        public string userId { get; set; }

        private AVCaptureSession captureSession;

        private AVCaptureDevice backCamera;
        private AVCaptureDevice frontCamera;

        private AVCaptureInput frontInput;
        private AVCaptureInput backInput;

        private AVCaptureVideoPreviewLayer previewLayer;

        private AVCaptureVideoDataOutput videoOutput;

       
        bool backCameraOn;

        public CameraViewController (IntPtr handle) : base (handle)
		{
		}

        #region Lifecycle
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            
        //    SetupView();
            backBtn.TouchUpInside += (sender, e) => DismissViewController(false, null);
            takePictureBtn.TouchUpInside += (sender, e) => Capture();
            rotateCameraBtn.TouchUpInside += (sender, e) => SwitchCameraInput();
         }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            //Check for permission first
            if (CheckPermission())
            {
                SetupAndStartCameraSession();
                notAvailableLabel.Hidden = true;
            }
            else
                notAvailableLabel.Hidden = false;
        }

        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);

            DisposeSources();
        }
        #endregion

        #region Methods

        public bool CheckPermission()
        {
            var permission = AVCaptureDevice.GetAuthorizationStatus(AVAuthorizationMediaType.Video);

            bool returningPermission = false;
            if (!CameraPermisiion)
            {
                if (permission == AVAuthorizationStatus.NotDetermined ||
                    permission == AVAuthorizationStatus.Denied)
                        AVCaptureDevice.RequestAccessForMediaType(AVAuthorizationMediaType.Video, p =>
                        {
                            if (p)
                                returningPermission = true;
                        });
                else
                    returningPermission = true;
            }
            else
                returningPermission = true;
            return returningPermission;
        }

        public void SetupAndStartCameraSession()
        {
            DispatchQueue.DefaultGlobalQueue.DispatchAsync(() =>
            {
                captureSession = new AVCaptureSession();
                captureSession.BeginConfiguration();

                // do some configs
                if (captureSession.CanSetSessionPreset(new NSString("photo")))
                    captureSession.SessionPreset = new NSString("photo");
                captureSession.AutomaticallyConfiguresCaptureDeviceForWideColor = true;

                SetupInputs();

                BeginInvokeOnMainThread(() => SetupPreviewLayer());

                SetupOutput();

                captureSession.CommitConfiguration();
                captureSession.StartRunning();

            });
        }
        public void SetupInputs()
        {

            frontCamera = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInWideAngleCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Front);
            backCamera = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInWideAngleCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Back);

            try
            {
                NSError inputError = new NSError();

                var input = new AVCaptureDeviceInput(frontCamera, out inputError);

                if(input != null)
                {
                    frontInput = input;
                }

                input = new AVCaptureDeviceInput(backCamera, out inputError);

                if (input != null)
                {
                    backInput = input;
                }

                if (captureSession.CanAddInput(frontInput))
                {
                    captureSession.AddInput(frontInput);
                    backCameraOn = false;
                }
                    

                 if (captureSession.CanAddInput(backInput))
                {
                     captureSession.AddInput(backInput);
                    backCameraOn = true;
                }
                   
            }
            catch 
            {
                notAvailableLabel.Hidden = false;
            }
        }

        public void SetupOutput()
        {
            videoOutput = new AVCaptureVideoDataOutput();
            var camOutput = new CameraOutput(this);

            var videoQueue = new DispatchQueue("videoQueue"); //qos : .userInteractive
       
            videoOutput.SetSampleBufferDelegateQueue(camOutput, videoQueue);

            if (captureSession.CanAddOutput(videoOutput))
                captureSession.AddOutput(videoOutput);
            else
                notAvailableLabel.Hidden = false;

            videoOutput.Connections[0].VideoOrientation = AVCaptureVideoOrientation.Portrait;
       
        }

        public void SetupPreviewLayer()
        {
            previewLayer = new AVCaptureVideoPreviewLayer(captureSession);
            View.Layer.InsertSublayer(previewLayer, 0);
            previewLayer.Frame = View.Layer.Frame;
        }

        public void Capture()
        {
            
            var output = captureSession.Outputs[0];

            captureSession.BeginConfiguration();
           takePicture = true;
           //WRITE NORM LOGIC
            captureSession.CommitConfiguration();
        }

        public void SwitchCameraInput()
        {
            rotateCameraBtn.UserInteractionEnabled = false ;
            captureSession.BeginConfiguration();

            if (backCameraOn)
            {
                captureSession.RemoveInput(backInput);
                captureSession.AddInput(frontInput);
                backCameraOn = false;
            }
            else
            {
                captureSession.RemoveInput(frontInput);
                captureSession.AddInput(backInput);
                backCameraOn = true;
            }
            videoOutput.Connections[0].VideoOrientation = AVCaptureVideoOrientation.Portrait;

            captureSession.CommitConfiguration();

            rotateCameraBtn.UserInteractionEnabled = true;
        }

       public void ShowPostView(UIImage img)
        {
            Action act = () =>
            {
                var editController = Storyboard.InstantiateViewController("EditingPostController") as EditingPostViewController;
                editController.images = new List<UIImage> { img };
                editController.userId = userId;

                takePicture = false;
                ShowViewController(editController, this);
            };
            BeginInvokeOnMainThread(act);
        }

        private void DisposeSources()
        {
            IDisposable[] toDispose = { captureSession, previewLayer, videoOutput };

            for(int i = 0; i < toDispose.Length; i++)
            {
                toDispose[i].Dispose();
                toDispose[i] = null;
            }
        }
        #endregion
    }

    public class CameraOutput: AVCaptureVideoDataOutputSampleBufferDelegate
    {
        CameraViewController cameraController;

        public CameraOutput(CameraViewController CameraController)
        {
            cameraController = CameraController;
        }

        public override void DidOutputSampleBuffer(AVCaptureOutput captureOutput, CMSampleBuffer sampleBuffer, AVCaptureConnection connection)
        {
            if (!cameraController.takePicture)
                return;
            var cvBuffer = sampleBuffer.GetImageBuffer();
            var ciImage = new CIImage(cvBuffer);
            var uiImage = new UIImage(ciImage);

            cameraController.ShowPostView(uiImage);
        }

        
    }
}
