// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using AVFoundation;
using CoreFoundation;

namespace ClipperIOS
{
	public partial class CameraViewController : UIViewController, IAVCaptureVideoDataOutputSampleBufferDelegate
	{
        private AVCaptureSession captureSession;

        private AVCaptureDevice backCamera;
        private AVCaptureDevice frontCamera;

        private AVCaptureInput frontInput;
        private AVCaptureInput backInput;

        private AVCaptureVideoPreviewLayer previewLayer;

        private AVCaptureVideoDataOutput videoOutput;

        bool takePicture = false;

        public CameraViewController (IntPtr handle) : base (handle)
		{
		}

        #region Lifecycle
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            SetupView();
            backBtn.TouchUpInside += (sender, e) => DismissViewController(false, null);
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            //Check for permission first
            notAvailableLabel.Hidden = true;

            SetupAndStartCameraSession();
        }
        #endregion

        #region Methods
        public void SetupAndStartCameraSession()
        {
            DispatchQueue.DefaultGlobalQueue.DispatchAsync(() =>
            {
                captureSession = new AVCaptureSession();
                captureSession.BeginConfiguration();

                // do some configs
                if (captureSession.CanSetSessionPreset(new NSString("photo")))
                    captureSession.SessionPreset = new NSString("photo");
                captureSession.AutomaticallyConfiguresCaptureDeviceForWideColor = true;

                SetupInputs();

                BeginInvokeOnMainThread(() => SetupPreviewLayer());

                SetupOutput();

                captureSession.CommitConfiguration();
                captureSession.StartRunning();

            });
        }

        public void SetupView()
        {

        }

        public void SetupInputs()
        {

            //TODO: if there`s no front or back camera
            frontCamera = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInWideAngleCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Front);
            backCamera = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInWideAngleCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Back);

            try
            {
                NSError inputError = new NSError();

                var input = new AVCaptureDeviceInput(frontCamera, out inputError);

                if(input != null)
                {
                    frontInput = input;
                }

                input = new AVCaptureDeviceInput(backCamera, out inputError);

                if (input != null)
                {
                    backInput = input;
                }

                if (!captureSession.CanAddInput(frontInput))
                    throw new Exception();

                captureSession.AddInput(frontInput);
                captureSession.AddInput(backInput);
            }
            catch
            {
                BeginInvokeOnMainThread(() => notAvailableLabel.Hidden = false);
            }
        }

        public void SetupOutput()
        {
            videoOutput = new AVCaptureVideoDataOutput();
            var videoQueue = new DispatchQueue("videoQueue"); //qos : .userInteractive
            videoOutput.SetSampleBufferDelegateQueue(this, videoQueue);

            if (captureSession.CanAddOutput(videoOutput))
                captureSession.AddOutput(videoOutput);
            else
                notAvailableLabel.Hidden = false;
        }

        public void SetupPreviewLayer()
        {
            previewLayer = new AVCaptureVideoPreviewLayer(captureSession);
            View.Layer.InsertSublayer(previewLayer, 0);
            previewLayer.Frame = View.Layer.Frame;
        }

        public void CaptureOutput() { }
        #endregion
    }
}
