// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ClipperIOS
{
	public partial class ProfileImgShortCell : UICollectionViewCell
	{
		public ProfileImgShortCell (IntPtr handle) : base (handle)
		{
		}
	}
}
