// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Clipper.ViewModels;
using CoreGraphics;
using Foundation;
using UIKit;

namespace ClipperIOS
{
	public partial class EditingPostViewController : UIViewController
	{
        private AddViewModel addViewModel;

        public string userId { get; set; }

		public List<UIImage> images;
        public List<string> uris;

		public EditingPostViewController (IntPtr handle) : base (handle)
		{

		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            scroll.Frame = new CGRect(0, 0, View.Frame.Width, View.Frame.Height*0.6f);

            foreach (var img in images)
            {
                var imgView = new UIImageView(
                    new CGRect(scroll.Frame.Width * images.IndexOf(img), 0,
                        scroll.Frame.Width, scroll.Frame.Height)
                    );
                imgView.ContentMode = UIViewContentMode.ScaleAspectFit ;
                imgView.Image = img;
                scroll.AddSubview(imgView);
            }

            scroll.ContentSize = new CGSize(scroll.Frame.Width*images.Count, scroll.Frame.Height);

            if (images.Count == 1)
                scroll.ScrollEnabled = false;

            pageCntrl.Pages = images.Count;
            
            scroll.Scrolled += (s, e) =>
            {
                var sc = s as UIScrollView;
                var offset = sc.ContentOffset.X;

                pageCntrl.CurrentPage = pageCntrl.Pages - ((int)Math.Round(sc.ContentSize.Width / (offset + sc.Frame.Width)));
            };

            txtBelow.EditingDidEndOnExit += (sender, e) => ResignFirstResponder();

            backBtn.TouchUpInside += (sender, e) =>
            {
                DismissViewController(false, null);
            };

            postBtn.TouchUpInside += (sender, e) => Post();
        }

        private async void Post()
        {
            addViewModel = new AddViewModel();

            if (txtBelow.Text != "")
                addViewModel.Title = txtBelow.Text;
            else
                addViewModel.Title = " ";

            uris = new List<string>();
            foreach (var i in images)
                uris.Add(ImageProcessing.SaveImg(i).ToString());
            addViewModel.Photos = uris;

            var successfully = addViewModel.AddNewPost(userId);

            string Message;

            if (successfully)
                Message = "Successfully posted!";
            else
                Message = "An error was occured";

            var presentingController = PresentingViewController;
            var root = presentingController as MainTabNavController;

            if (root == null)
            {
                //dismissParentControllerAction = new Action(()=> PresentingViewController.DismissViewController(false, null));

                var fatherRoot = presentingController.PresentingViewController as MainTabNavController;
                DismissViewController(false, () =>
                {
                    fatherRoot.SelectedViewController = fatherRoot.ViewControllers
                                                        .Where(controller => controller is MainFlowViewController)
                                                        .FirstOrDefault();
                    presentingController.DismissViewController(false, null);
                });
            }
            else
            {
                var newPostViewController = root.SelectedViewController as NewPostViewController;
                newPostViewController.Reset();
                root.SelectedViewController = root.ViewControllers.Where(vc => vc is MainFlowViewController).FirstOrDefault();

                var profileController = root.ViewControllers.Where(vc => vc is ProfileViewController).FirstOrDefault() as ProfileViewController;

                profileController.Settings ??= root.Settings;

                (this as UIViewController).ShowToast(Message, 3);

                await profileController.UpdateCollectionInBackground();
                var dismissParentControllerAction = new Action(() => newPostViewController.DismissViewController(false, null));
                DismissViewController(false, dismissParentControllerAction);
            }
          
        }
    }
}
