// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ClipperIOS
{
	public partial class PhotoShortCut : UICollectionViewCell
	{
		public PhotoShortCut (IntPtr handle) : base (handle)
		{
		}
	}
}
